### ISSUE TITLE
Check for Gutenberg compatibility

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/spcl#10]
WordPress 5.0 will be here soon. Time for us to check, if our plugins are compatible with the Gutenberg Editor and WP 5.0 (a beta version is yet to be published). 

- [x] check (Gutenberg) editor with this plugin
- [ ] check plugin settings site with active Gutenberg
- [ ] fix potential issues
- [ ] add `Tested up to: 5.0` to the plugins readme
- [ ] publish changes as minor update or with upcoming plugin update

**Comment by patrickrobrecht** [comment]
SPCL is not compatible with Gutenberg yet, but it is compatible until 4.9.x (see #11).

**Comment by patrickrobrecht** [comment]
Some months ago, I started to make SPCL compatible with Gutenberg (branch gutenberg). The remaining problem is that the error messages are not updated after saving because Gutenberg does not reload the whole editor page (as the classic editor did).

**Comment by Zodiac1978** [comment]
@florianbrinkmann Can you help to get this Gutenberg-ready?

**Comment by florianbrinkmann** [comment]
Yes, will take a look at it.

**Comment by florianbrinkmann** [comment]
@Zodiac1978 and @patrickrobrecht I created a PR (https://github.com/pluginkollektiv/spcl/pull/14) that should add Gutenberg compatibility.
