### ISSUE TITLE
Only check links on demand

### ISSUE THREAD

**Issue by patrickrobrecht** [pluginkollektiv/spcl#24]
First suggested on the [support forum](https://wordpress.org/support/topic/feature-request-choose-whether-to-check/):

> But I also don’t necessarily need to check all the links in a post every time I update it, so that seems resource-heavy for both me and the destination sites. I would LOVE, rather than having this check automatically on save, to have a button in the editing pane that will check the links in the post when I click on it. I’m not a programmer, though, so I don’t know how much more work that is to create.

**Comment by Zodiac1978** [comment]
I'm not sure if this aligns with the goal of this plugin:

> When a post is saved or published, this plugin will
> 
>     scan the post’s content for any URLs,
>     ping all the URLs found (except relative ones),
>     detect any broken or unreachable URLs and list them for review and correction.

Pinging websites (without content, just headers) is not very resource heavy. We do not need to re-check some links (like Medium or LinkedIn) which will never work, but this is already tracked in another issue: #9 

I recommend closing this issue.
